version: '3.8'

services:
  django:
    build:
      context: ./django_service
      dockerfile: ./Dockerfile.prod
    command: /start.sh
    expose:
      - 8000
    volumes:
      - ./django_service:/app
      - staticfiles:/app/staticfiles
    env_file: ./.env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    expose:
      - 6379

  celery_worker:
    build:
      context: ./django_service
      dockerfile: ./Dockerfile.prod
    volumes:
      - ./django_service:/app
    command: celery -A {{ project_name }} worker -l INFO
    env_file:
      - ./.env
    depends_on:
      - django

  celery_beat:
    build:
      context: ./django_service
      dockerfile: ./Dockerfile.prod
    volumes:
      - ./django_service:/app
    command: celery -A {{ project_name }} beat -l INFO
    env_file:
      - ./.env
    depends_on:
      - django

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    volumes:
      # nginx config files
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/snippets:/etc/nginx/snippets
      # django static files
      - staticfiles:/app/staticfiles
      # certbot
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/nginx/ssl

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - nginx

volumes:
  staticfiles:
