version: '3.8'

services:
  django:
    build: ./django_service
    command: /start
    expose:
      - 8000
    volumes:
      - ./django_service:/app
      - staticfiles:/app/staticfiles
    env_file: ./.env
  
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      # nginx config files
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/dev:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      # django static files
      - staticfiles:/app/staticfiles

volumes:
  staticfiles: