version: '3.8'

services:
  django:
    build: ./django_service
    command: /start.sh
    expose:
      - 8000
    volumes:
      - ./django_service:/app
      - staticfiles:/app/staticfiles
    environment:
      - SECRET_KEY='123'
      - REDIS_URL='redis://redis:6379/0'
      - GOOGLE_ANALYTICS_ID
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    expose:
      - 6379

  celery_worker:
    build: ./django_service
    volumes:
      - ./django_service:/app
    command: celery -A {{project_name}} worker -l INFO
    environment:
      - SECRET_KEY='123'
      - REDIS_URL='redis://redis:6379/0'
      - GOOGLE_ANALYTICS_ID
    depends_on:
      - django

  celery_beat:
    build: ./django_service
    volumes:
      - ./django_service:/app
    command: celery -A {{project_name}} beat -l INFO
    environment:
      - SECRET_KEY='123'
      - REDIS_URL='redis://redis:6379/0'
      - GOOGLE_ANALYTICS_ID
    depends_on:
      - django

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - django
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    volumes:
      # nginx config files
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      # django static files
      - staticfiles:/app/staticfiles

volumes:
  staticfiles:
